name: "nbdev-deploy-private"
description: "Test and deploy nbdev to private"
inputs:
  ghtoken:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps: 
    - name: Nbdev ci
      uses: fastai/workflows/nbdev-ci@master

    - name: Build Nbdev Docs
      run: nbdev_docs
      shell: bash

    - name: Create Email List
      working-directory: ./_docs
      shell: bash
      run: |
        cat << 'EOF' >> email_list.txt
        rahuketu86@gmail.com
        rahul.sarafiitk@gmail.com
        EOF

    - name: Create DockerFile
      working-directory: ./_docs
      shell: bash
      run: |
        cat << 'EOF' >> Dockerfile
        FROM quay.io/oauth2-proxy/oauth2-proxy
        COPY email_list.txt /site_config/
        COPY . /app/
        ENTRYPOINT ["/bin/oauth2-proxy", \
                    "--provider", "github", \
                    "--upstream", "file:///app/#/", \
                    "--authenticated-emails-file", "/site_config/email_list.txt", \
                    "--cookie-expire=0h0m30s", \
                    "--session-cookie-minimal=true", \
                    "--skip-provider-button=true"]
        EOF
        
    - name: Create Render file
      working-directory: ./_docs
      shell: bash
      run: |
        cat << 'EOF' >> render.yaml
        services:
          - type: web
            name: oauth2-proxy-render
            plan: free
            env: docker
            envVars:
              - key: OAUTH2_PROXY_CLIENT_ID
                sync: false
              - key: OAUTH2_PROXY_CLIENT_SECRET
                sync: false
              - key: OAUTH2_PROXY_COOKIE_SECRET
                generateValue: true
              - key: OAUTH2_PROXY_HTTP_ADDRESS
                value: ":10000"
        EOF

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.ghtoken }}
        force_orphan: true
        publish_dir: ./_docs
        # The following lines assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch.
        # You can swap them out with your own user credentials.
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
